"""Phase 2: connecting workforce identities to jobs.

Phase 1 defined who exists and what each identity may do. This links those
identities to actual work, and adds the one rule Phase 1 could not express:

  **A job a synthetic head generates must say what caused it.**

Without that, a department head can create work that creates work with nothing
tying the tree back to an owner intent. The traceability requirement then exists
only in a document, which is the definition of a false control. So the rule is
enforced *at construction*: `create_generated_job` refuses a job with no origin,
and there is no way to build one that bypasses it other than writing to the store
directly -- which is a different act, not an accident.

Everything here is additive. Existing jobs have no department and no origin, and
they keep working: `traceability` reports them as untraced rather than invalid,
because "filed by a human" and "generated by a head with no stated reason" are
different things and only the second is a defect.

Identity handling follows the rule this project learned the hard way: ids are
validated before they are compared. A raw `==` on two strings made Phase 1's
central rule bypassable by a case change, and the same mistake here would let a
worker be "assigned" under a near-miss identity that matches no real worker.
"""

from __future__ import annotations

from typing import Any

from connector.schema import Job, Risk, Status, TaskKind, new_job_id
from connector.store import Store

from .delegation import can_delegate
from .registry import WorkforceRegistry
from .schema import valid_id
from .verification import can_verify


class OriginRequired(ValueError):
    """Raised when a synthetic-generated job states no origin."""


def _require_known_identity(registry: WorkforceRegistry, value: str, label: str) -> None:
    """Validate an id before it is used, not when it is compared.

    `valid_id` rejects anything that is not a canonical lowercase id, so a
    near-miss (case, whitespace, hyphen-for-underscore) fails here as an
    *invalid id* rather than silently becoming a different identity downstream.
    """
    if not valid_id(value):
        raise ValueError(
            f"{label} {value!r} is not a valid id; ids are lowercase and stable, "
            "so a near-miss is a different identity"
        )
    if registry.worker(value) is None:
        raise ValueError(f"{label} {value!r} is not a known worker")


def _require_known_department(registry: WorkforceRegistry, value: str) -> None:
    if not valid_id(value):
        raise ValueError(f"department {value!r} is not a valid id")
    if registry.department(value) is None:
        raise ValueError(f"department {value!r} is not a known department")


def create_generated_job(
    store: Store,
    registry: WorkforceRegistry,
    *,
    department_id: str,
    requested_by: str,
    kind: TaskKind,
    title: str,
    payload: dict | None = None,
    risk: Risk = Risk.LOW,
    origin_objective: str | None = None,
    origin_job_id: str | None = None,
    assigned_worker: str | None = None,
) -> Job:
    """Create a job generated by a synthetic department head.

    Refuses unless the job can be traced to an objective or a parent job. This
    is the only supported way for a head to create work, which is what makes the
    traceability rule real rather than advisory.
    """
    _require_known_department(registry, department_id)
    _require_known_identity(registry, requested_by, "requested_by")
    if assigned_worker is not None:
        _require_known_identity(registry, assigned_worker, "assigned_worker")

    if not (origin_objective or origin_job_id):
        raise OriginRequired(
            "a synthetic-generated job must name its origin: set origin_objective "
            "or origin_job_id, or file the job as a human request instead"
        )
    if origin_job_id is not None:
        # A parent that does not exist would make the tree unverifiable while
        # still looking traceable.
        if store.get_job(origin_job_id) is None:
            raise ValueError(f"origin_job_id {origin_job_id!r} does not exist")

    requested_by_dept = registry.worker(requested_by).department_id
    if requested_by_dept != department_id:
        raise ValueError(
            f"{requested_by!r} belongs to {requested_by_dept!r}, not {department_id!r}"
        )

    payload = payload or {}
    job = Job(
        job_id=new_job_id(kind, title, payload),
        kind=kind,
        title=title,
        payload=payload,
        risk=risk,
        assigned_department=department_id,
        assigned_worker=assigned_worker,
        requested_by=requested_by,
        origin_objective=origin_objective,
        origin_job_id=origin_job_id,
    )
    store.create_job(job, actor=requested_by)
    # The generated job must be delegable to whoever it names, or the head has
    # created work nothing is permitted to do.
    if assigned_worker is not None:
        d = can_delegate(registry, assigned_worker, job_risk=risk)
        if not d.allowed:
            raise ValueError(
                f"{assigned_worker!r} may not take this job: {d.reason}"
            )
    return job


def assign_job(
    store: Store,
    registry: WorkforceRegistry,
    job_id: str,
    worker_id: str,
    *,
    actor: str,
    approved: bool = False,
    paused: bool = False,
) -> Job:
    """Assign an existing job to a worker, honouring every Phase 1 boundary."""
    _require_known_identity(registry, worker_id, "worker_id")
    job = store.get_job(job_id)
    if job is None:
        raise ValueError(f"unknown job {job_id!r}")

    d = can_delegate(
        registry, worker_id, job_risk=job.risk, job_status=job.status,
        paused=paused, approved=approved,
    )
    if not d.allowed:
        raise ValueError(f"{worker_id!r} may not take {job_id}: {d.reason}")

    worker = registry.worker(worker_id)
    job.assigned_worker = worker_id
    job.assigned_department = worker.department_id
    return store._update(job, actor, "job.assigned", worker_id=worker_id)


def record_verification_worker(
    store: Store,
    registry: WorkforceRegistry,
    job_id: str,
    verifier_id: str,
    *,
    actor: str,
) -> Job:
    """Record who is *assigned* to check a job.

    Refuses a verifier that could not legitimately verify it, which is the same
    refusal `verify` will make later -- checking it here means an impossible
    assignment fails at assignment time rather than at the moment verification
    was supposed to happen.
    """
    _require_known_identity(registry, verifier_id, "verifier_id")
    job = store.get_job(job_id)
    if job is None:
        raise ValueError(f"unknown job {job_id!r}")

    producer = job.assigned_worker or job.requested_by
    if producer is not None:
        d = can_verify(registry, producer, verifier_id)
        if not d.allowed:
            raise ValueError(
                f"{verifier_id!r} may not verify {job_id}: {d.reason}"
            )
    job.verification_worker = verifier_id
    return store._update(job, actor, "job.verifier_assigned", verifier_id=verifier_id)


def traceability(job: Job) -> dict[str, Any]:
    """Report how a job traces to an owner intent, and whether it must.

    A job with no department is *untraced*, not *invalid*: it predates this
    feature or was filed by a human. Only a job that names a synthetic
    department and no origin is a defect, and this says which is which rather
    than collapsing both into a single "missing" flag.
    """
    synthetic = job.assigned_department is not None
    has_origin = bool(job.origin_objective or job.origin_job_id)
    if not synthetic:
        state = "not-synthetic"          # human-filed or legacy; no rule applies
    elif has_origin:
        state = "traced"
    else:
        state = "untraced-defect"
    return {
        "job_id": job.job_id,
        "state": state,
        "department": job.assigned_department,
        "origin_objective": job.origin_objective,
        "origin_job_id": job.origin_job_id,
        "verification_worker": job.verification_worker,
        "verified": job.verified,
    }


def untraced_jobs(store: Store) -> list[Job]:
    """Synthetic-generated jobs with no stated origin. Should always be empty.

    Exposed as a query so this can be checked rather than assumed -- the whole
    point of enforcing the rule at construction is that this list is provably
    empty on any store written through `create_generated_job`.
    """
    return [j for j in store.jobs() if traceability(j)["state"] == "untraced-defect"]
